"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.frAlphabet = exports.binAlphabet = exports.enAlphabet = exports.ruAlphabet = void 0;
var ruAlphabet = 'абвгдежзийклмнопрстуфхцчшщъыьэюя ';
exports.ruAlphabet = ruAlphabet;
var enAlphabet = 'abcdefghijklmnopqrstuvwxyz ';
exports.enAlphabet = enAlphabet;
var frAlphabet = 'abcdefghijklmnopqrstuvwxyz';
exports.frAlphabet = frAlphabet;
var binAlphabet = '01';
exports.binAlphabet = binAlphabet;
